### PR TITLE
[v2.8] Add system-agent script URL to the default value of `SystemAgentInstallScript`

### LINKED ISSUE #44682: [BUG] RKE2/K3S registration command not working on airgap setup
**Rancher Server Setup**
- Rancher version: v2.8.3-rc2
- Installation option (Docker install/Helm Chart): docker airgap
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.28.6+rke2r1/v1.28.6+k3s2
- Cluster Type (Local/Downstream): 
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin
  - If custom, define the set of permissions:

**Describe the bug**

- In Airgap setup RKE2 and K3s custom clusters registration command on nodes is failing with below error:
```
curl: (22) The requested URL returned error: 500 
```

**To Reproduce**

- Create v2.8.3-rc2 docker airgap setup.
- Create nodes on AWS for RKE2 or K3s custom cluster.
- SSH into bastion node and then SSH into node created for custom cluster above.
- Run the registration command and observe that it fails with `curl: (22) The requested URL returned error: 500`

**Result**
- Cluster registration command fails.

**Expected Result**

- Cluster registration command should run successfully.

### PR DESCRIPTION
**Pull request by chiukapoor**
## Issue:
* https://github.com/rancher/rancher/issues/44682
 
## Problem
* Described in comment https://github.com/rancher/rancher/issues/44682#issuecomment-1980762917
 
## Solution
* Add system-agent script URL to the default value of `SystemAgentInstallScript`

### CODE REVIEW

File: pkg/settings/setting.go [hunk 1]
```diff
@@ -96,7 +96,7 @@ var (
 	WinsAgentVersion                    = NewSetting("wins-agent-version", "")
 	CSIProxyAgentVersion                = NewSetting("csi-proxy-agent-version", "")
 	CSIProxyAgentURL                    = NewSetting("csi-proxy-agent-url", "https://acs-mirror.azureedge.net/csi-proxy/%[1]s/binaries/csi-proxy-%[1]s.tar.gz")
-	SystemAgentInstallScript            = NewSetting("system-agent-install-script", "") // Defined via environment variable
+	SystemAgentInstallScript            = NewSetting("system-agent-install-script", "https://github.com/rancher/system-agent/releases/download/v0.3.5-rc1/install.sh") // Defined via environment variable
```
Comment (Oats87) [inline pkg/settings/setting.go:99]: I've been giving this some thought.

Rather than define an identical value here as a default, perhaps we should do this
1. Rename the `ENV CATTLE_SYSTEM_AGENT_INSTALL_SCRIPT` to something like `ENV DEFAULT_CATTLE_SYSTEM_AGENT_INSTALL_SCRIPT` and update subsequent references to it
2. Change this to `os.Getenv("DEFAULT_CATTLE_SYSTEM_AGENT_INSTALL_SCRIPT")`

This will bring the business logic back into the realm of doing what it is supposed to, i.e. if the system agent install script is NOT the default value, retrieve from URL, otherwise trust what is on disk.

The ideal fix would actually be to properly inject the system-agent-install-script default setting value at build time, but that is a can of worms I don't think is worth trying to open right now.

**Review by Oats87 — CHANGES_REQUESTED** [review]

File: pkg/settings/setting.go (hunk 1 above)
Comment (Oats87) [reply pkg/settings/setting.go:99]: If we want to stick with this approach, then please expand upon the comment here. You should make sure that we have behavior built into Rancher that relies upon the default value being hardcoded.

Comment (chiukapoor) [reply pkg/settings/setting.go:99]: @Oats87 will PR https://github.com/rancher/rancher/pull/44687 suffice as a fix?

Comment (chiukapoor) [reply pkg/settings/setting.go]: Updated the comment.

**Review by Oats87 — APPROVED** [review]

**Review by jakefhyde — APPROVED** [review]
