### PR TITLE
Display drain errors on machine

### LINKED ISSUE #36763: RKE2 | Custom cluster | Cluster stays in Provisioning state after adding a Windows node
**Rancher Server Setup**
- Rancher version: v2.6-head 3659d2f
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.21 and v1.22
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom

  
**Describe the bug**

Cluster stays in Provisioning state after adding a Windows node even though the node is added and machine is created for it

**To Reproduce**
 
1. Create a RKE2 custom cluster (1 etcd, 1 cp, 1 worker)
2. Add a windows node 

**Result**
The cluster stays in the Provisioning state

**Expected Result**

The cluster goes into the Active state after a node is added successfully with a machine created

**Screenshots**

cluster

**Additional context**

Rancher logs:
```
2022/03/04 17:01:00 [INFO] [planner] rkecluster fleet-default/win121: waiting: provisioning worker node(s) custom-249aaa0b4d98
2022/03/04 17:02:35 [INFO] [planner] rkecluster fleet-default/win122: waiting: provisioning worker node(s) custom-5f36b9e03dbd
2022/03/04 17:02:45 [INFO] [planner] rkecluster fleet-default/win122: waiting: provisioning worker node(s) custom-5f36b9e03dbd
2022/03/04 17:07:29 [ERROR] Unknown error: Operation cannot be fulfilled on preferences.management.cattle.io "cluster": the object has been modified; please apply your changes to the latest version and try again
2022/03/04 17:08:58 [INFO] [planner] rkecluster fleet-default/windows: waiting: provisioning worker node(s) custom-fc77ed38b0d9
2022/03/04 17:09:08 [INFO] [planner] rkecluster fleet-default/windows: waiting: provisioning worker node(s) custom-fc77ed38b0d9
2022/03/04 17:10:51 [INFO] [planner] rkecluster fleet-default/win121: waiting: provisioning worker node(s) custom-249aaa0b4d98
2022/03/04 17:11:01 [INFO] [planner] rkecluster fleet-default/win121: waiting: provisioning worker node(s) custom-249aaa0b4d98
```

### PR DESCRIPTION
**Pull request by thedadams**
Issues:
https://github.com/rancher/rancher/issues/36506
https://github.com/rancher/rancher/issues/36782
https://github.com/rancher/rancher/issues/35999
https://github.com/rancher/rancher/issues/36776
https://github.com/rancher/rancher/issues/36763

## Problems
During provisioning and upgrading, there were no statuses being put on the machine objects. Therefore, if there was a problem with a specific machine, one would have to look at the cluster status, find the machine name, and look at that specific machine to attempt to understand what was happening. This change adds the status (to either Provisioned or Updated conditions) so the proper status is shown directly in the UI. (#36782)

Now, that we are properly showing statuses on the machine objects, we can now show errors statuses as well when they occur. That way a user doesn't have to comb through the logs or connect to the VM/node directly. (#36506)

These statuses now make using the upgrade strategy more reliable. Since the statuses are being directly put on the machines, Rancher is able to calculate the unavailable nodes in a more robust way to ensure that, for example, if a control plane node is still upgrading then the worker nodes will not upgrade. (#35999)

Also, consider the case above with etcd nodes. An etcd node is always the bootstrap node. So, when upgrading a cluster, the boostrap node would get upgraded first. After the bootstrap node is upgraded, then the remaining etcd nodes are upgraded. Since Rancher was mistakenly not waiting for nodes to be upgraded before moving onto the next group of nodes, multiple etcd nodes could be upgrading at the same time. This is dangerous and could cause data integrity issues. Thus, the robustness of determining when to move onto the next group of nodes also fixes this problem. For good measure, Rancher will now only upgrade one etcd node at a time. (#36776)

Lastly, Windows nodes report a different kubelet version from linux nodes (they don't have the +rke2rx on the end). A check for kubelet version was added in a different PR to delay upgrading worker nodes before control plane nodes were completed. This change is no longer needed with the above enhancements and this will fix #36763

## Testing
I tested provisioning, upgrading, and deleting of the following types of clusters.
- single node all roles with and without draining enabled
- one node all roles and one node worker-only with and without draining enabled
- 3 etcd nodes 2 control plane nodes and 1 worker node with draining enabled
- one node all roles and one node worker-only with draining enabled, but misconfigured. I ensured that the error appeared in the UI. Then fixed the draining misconfiguration so that draining and upgrading would continue.

### CODE REVIEW

File: pkg/controllers/provisioningv2/rke2/machinedrain/machinedrain.go [hunk 1]
```diff
@@ -35,35 +33,17 @@ type handler struct {
...
 	h := &handler{
 		ctx:          ctx,
+		machines:     clients.CAPI.Machine(),
 		machineCache: clients.CAPI.Machine().Cache(),
 		secrets:      clients.Core.Secret(),
 		secretCache:  clients.Core.Secret().Cache(),
 	}
 
-	// It would be a bad idea to have this handler run for every secret. Therefore, a new cache factory is created just for secrets with the machine plan type.
-	cacheFactory := cache.NewSharedCachedFactory(clients.ControllerFactory.SharedCacheFactory().SharedClientFactory(), &cache.SharedCacheFactoryOptions{
```
Comment (thedadams) [inline pkg/controllers/provisioningv2/rke2/machinedrain/machinedrain.go:44]: I put this in previously because:
1. I thought I was being clever, and
2. I thought watching all secrets would be bad performance, but we are already doing that in several places.

So that is why I am removing this now.

**Comment by Oats87** [comment]
Are the changes in this PR are causing provisioning times to increase?

**Review by paynejacob — APPROVED** [review]

File: pkg/controllers/provisioningv2/rke2/machinedrain/machinedrain.go [hunk 2]
```diff
@@ -72,21 +52,33 @@ func (h *handler) OnChange(_ string, secret *corev1.Secret) (*corev1.Secret, err
 		return secret, err
 	}
 
+	defer func() {
+		if machine == nil ||
+			err == nil && !rke2.NodeDrained.IsFalse(machine) ||
+			err != nil && rke2.NodeDrained.GetMessage(machine) == err.Error() {
```
Comment (jiaqiluo) [inline pkg/controllers/provisioningv2/rke2/machinedrain/machinedrain.go:58]:
```suggestion
		if machine == nil ||
			(err == nil && !rke2.NodeDrained.IsFalse(machine)) ||
			(err != nil && rke2.NodeDrained.GetMessage(machine) == err.Error()) {
```

Comment (jiaqiluo) [reply pkg/controllers/provisioningv2/rke2/machinedrain/machinedrain.go:58]: We need the `()`, right?

**Review by jiaqiluo — CHANGES_REQUESTED** [review]

**Comment by snasovich** [comment]
@thedadams , after discussing with QA we're bumping this issue until 2.6.5, so let's not merge this one yet.

File: pkg/provisioningv2/rke2/planner/drain.go [hunk 3]
```diff
@@ -85,5 +92,21 @@ func (p *Planner) undrain(entry *planEntry) (bool, error) {
 		return false, p.store.updatePlanSecretLabelsAndAnnotations(entry)
 	}
 
+	if err := checkForDrainError(entry, "undraining"); err != nil {
+		// This is the only place true and an error is returned to indicate that draining is ongoing, but there is an error.
```
Comment (jakefhyde) [inline pkg/provisioningv2/rke2/planner/drain.go:96]:
```suggestion
		// This is the only place true and an error is returned to indicate that undraining is ongoing, but there is an error.
```

File: pkg/controllers/provisioningv2/rke2/machinedrain/machinedrain.go [hunk 4]
```diff
@@ -244,3 +240,17 @@ func (h *handler) performDrain(machine *capi.Machine, drainOpts *rkev1.DrainOpti
 
 	return drain.RunNodeDrain(helper, node.Name)
 }
+
+func (h *handler) updateSecretAnnotation(secret *corev1.Secret, annotation, value string) (*corev1.Secret, error) {
+	var err error
+	return secret, retry.RetryOnConflict(retry.DefaultRetry, func() error {
```
Comment (Oats87) [inline pkg/controllers/provisioningv2/rke2/machinedrain/machinedrain.go:246]: I wonder if using a `retry` here can run us into weird edge cases where the drain/uncordon annotations are being manipulated in rapid succession.

If anything, I would almost want to do a `retry.RetryOnConflict` where we validate that the annotations we care about (the drain/uncordon ones) are in the "old" set state before we update them -- we should easily be able to pass in the current values/keys we care about to compare against.

File: pkg/provisioningv2/rke2/planner/drain.go [hunk 5]
```diff
@@ -85,5 +92,21 @@ func (p *Planner) undrain(entry *planEntry) (bool, error) {
...
+		return true, err
+	}
+
+	// The annotations will be removed when undrain is done
 	return entry.Metadata.Annotations[rke2.UnCordonAnnotation] == "", nil
 }
+
+func checkForDrainError(entry *planEntry, drainStep string) error {
```
Comment (Oats87) [inline pkg/provisioningv2/rke2/planner/drain.go:104]: Can we make this a godoc comment to indicate the scope of this functionality is only for looking for transient connectivity errors?

File: pkg/provisioningv2/rke2/planner/planner.go [hunk 6]
```diff
@@ -163,6 +165,88 @@ func New(ctx context.Context, clients *wrangler.Context) *Planner {
...
+	if waiting {
+		return ErrWaiting(messagePrefix + atMostThree(machineNames) + detailMessage(machineNames, messages))
+	}
+	return nil
+}
+
+func atMostThree(names []string) string {
+	sort.Strings(names)
+	if len(names) > 3 {
+		return strings.Join(names[:3], ",")
```
Comment (Oats87) [inline pkg/provisioningv2/rke2/planner/planner.go:213]: Should we add some type of indicator here to indicate that there are in fact more than 3 `names`? like a `and more` or something

File: pkg/provisioningv2/rke2/planner/planner.go [hunk 7]
```diff
@@ -179,10 +263,10 @@ func (p *Planner) getCAPICluster(controlPlane *rkev1.RKEControlPlane) (*capi.Clu
...
 	logrus.Debugf("[planner] rkecluster %s/%s: attempting to lock %s for processing", controlPlane.Namespace, controlPlane.Name, string(controlPlane.UID))
 	p.locker.Lock(string(controlPlane.UID))
-	defer func() error {
-		logrus.Debugf("[planner] rkecluster %s/%s: unlocking %s", controlPlane.Namespace, controlPlane.Name, string(controlPlane.UID))
-		return p.locker.Unlock(string(controlPlane.UID))
-	}()
+	defer func(namespace, name, uid string) error {
+		logrus.Debugf("[planner] rkecluster %s/%s: unlocking %s", namespace, name, uid)
+		return p.locker.Unlock(uid)
+	}(controlPlane.Namespace, controlPlane.Name, string(controlPlane.UID))
```
Comment (Oats87) [inline pkg/provisioningv2/rke2/planner/planner.go:269]: so, I'm assuming you added this because you saw a panic here; however, do you know where we are causing the `RKEControlPlane` to be set to nil...? Just for posterity purposes -- I avoided passing the parameters through the func signature because I didn't think we would be hitting a situation where `controlPlane` would become nil.

File: pkg/provisioningv2/rke2/planner/planner.go [hunk 8]
```diff
@@ -438,70 +510,89 @@ func (p *Planner) reconcile(controlPlane *rkev1.RKEControlPlane, tokensSecret pl
...
+		} else if entry.Machine.Status.NodeInfo != nil && !strings.HasPrefix(controlPlane.Spec.KubernetesVersion, entry.Machine.Status.NodeInfo.KubeletVersion) {
+			outOfSync = append(outOfSync, entry.Machine.Name)
+			messages[entry.Machine.Name] = append(messages[entry.Machine.Name], "waiting for kubelet to update")
+		} else {
+			ready = append(ready, entry.Machine.Name)
 		}
 	}
 
-	if required && len(entries) == 0 {
+	if len(entries) == 0 && tierName != "worker" {
```
Comment (Oats87) [inline pkg/provisioningv2/rke2/planner/planner.go:557]: this change removes flexibility from the framework.... I suppose we can re-add it if we need it at a later time.

File: pkg/provisioningv2/rke2/planner/planner.go [hunk 9]
```diff
@@ -163,6 +165,88 @@ func New(ctx context.Context, clients *wrangler.Context) *Planner {
...
+	var waiting bool
+	for _, machineName := range machineNames {
+		machine := clusterPlan.Machines[machineName]
+		if machine == nil {
+			return fmt.Errorf("found unexpected machine %s that is not in cluster plan", machineName)
+		}
+
+		cond = rke2.Provisioned
+		if rke2.Provisioned.IsTrue(machine) {
+			cond = rke2.Updated
```
[the remark this answers is not in the document]
Comment (thedadams) [reply pkg/provisioningv2/rke2/planner/planner.go:179]: After the machine has the `Provisioned` condition set to true, then we will be editing the `Updated` condition. The `Provisioned` condition will be set to true below (line 196).

File: pkg/controllers/provisioningv2/rke2/machinedrain/machinedrain.go [hunk 10]
```diff
@@ -72,21 +50,45 @@ func (h *handler) OnChange(_ string, secret *corev1.Secret) (*corev1.Secret, err
 		return secret, err
 	}
 
+	oldSecret := secret.DeepCopy()
+	defer func() {
+		if secret == nil || secret.Annotations == nil {
```
[the remark this answers is not in the document]
Comment (thedadams) [reply pkg/controllers/provisioningv2/rke2/machinedrain/machinedrain.go:55]: The closure doesn't keep the state at the time it was created. So, if one of the functions below returns a `nil` secret, then it will be `nil` when this `defer` runs.

File: pkg/controllers/provisioningv2/rke2/machinedrain/machinedrain.go [hunk 11]
```diff
@@ -72,21 +50,45 @@ func (h *handler) OnChange(_ string, secret *corev1.Secret) (*corev1.Secret, err
...
+			secret.Annotations[rke2.DrainErrorAnnotation] = err.Error()
+		} else {
+			delete(secret.Annotations, rke2.DrainErrorAnnotation)
+		}
+
+		var updateErr error
+		if secret, updateErr = h.secrets.Update(secret); updateErr != nil && err == nil {
+			err = updateErr
+		} else if updateErr != nil {
+			logrus.Errorf("Failed to update secret %s/%s with drain error annotation: %v", secret.Namespace, secret.Name, updateErr)
```
[the remark this answers is not in the document]
Comment (thedadams) [reply pkg/controllers/provisioningv2/rke2/machinedrain/machinedrain.go:75]: Yes, I will take a stab at this.

File: pkg/controllers/provisioningv2/rke2/machinedrain/machinedrain.go (hunk 4 above)
Comment (thedadams) [reply pkg/controllers/provisioningv2/rke2/machinedrain/machinedrain.go:246]: The reason I had to add this retry is because the `system-agent` is also updating the plan secret every second while the upgrade/drain is happening. I am unsure if removing this will allow the updating of the secret to be successful.

File: pkg/controllers/provisioningv2/rke2/provisioningcluster/template.go [hunk 12]
```diff
@@ -407,6 +407,7 @@ func machineDeployments(cluster *rancherv1.Cluster, capiCluster *capi.Cluster, d
 					ObjectMeta: capi.ObjectMeta{
 						Labels: map[string]string{
 							capi.ClusterLabelName:           capiCluster.Name,
+							rke2.ClusterNameLabel:           capiCluster.Name,
```
[the remark this answers is not in the document]
Comment (thedadams) [reply pkg/controllers/provisioningv2/rke2/provisioningcluster/template.go:410]: Yes, but that is already going to happen when a user upgrades to 2.6.4 because of some other changes we made. I am hoping we can get all these types of changes into 2.6.4 so it doesn't have to happen again.

File: pkg/provisioningv2/rke2/planner/drain.go (hunk 5 above)
Comment (thedadams) [reply pkg/provisioningv2/rke2/planner/drain.go:104]: Yes, I will add a comment.

File: pkg/provisioningv2/rke2/planner/planner.go (hunk 6 above)
Comment (thedadams) [reply pkg/provisioningv2/rke2/planner/planner.go:213]: Yes I can do that.

File: pkg/provisioningv2/rke2/planner/planner.go (hunk 8 above)
Comment (thedadams) [reply pkg/provisioningv2/rke2/planner/planner.go:557]: You're right, but I was just trying to simplify the signature of `reconcile`. I can switch it back if you'd like.

File: pkg/provisioningv2/rke2/planner/planner.go (hunk 7 above)
Comment (thedadams) [reply pkg/provisioningv2/rke2/planner/planner.go:269]: The method `generateSecrets` on line 281 could return a `nil` `controlPlane`.

I can switch this back and ensure that method doesn't return a `nil` `controlPlane`, but this seemed safer to me so that if any other situation might get us into a `nil` `controlPlane` (now or in the future), then this protects us.

File: pkg/controllers/provisioningv2/rke2/machinedrain/machinedrain.go (hunk 4 above)
Comment (Oats87) [reply pkg/controllers/provisioningv2/rke2/machinedrain/machinedrain.go:247]: I'm not saying we should remove the retry, I'm saying we should validate the before settings of the annotations being what we expect before we manipulate the latest secret we retrieve.

Comment (thedadams) [reply pkg/controllers/provisioningv2/rke2/machinedrain/machinedrain.go:247]: Ah. I misunderstood. Yes, I will add this.

File: pkg/provisioningv2/rke2/planner/drain.go (hunk 5 above)
Comment (Oats87) [reply pkg/provisioningv2/rke2/planner/drain.go:107]: I understand the functionality here. The name of the function is vague.

File: pkg/provisioningv2/rke2/planner/planner.go (hunk 9 above)
[the remark this answers is not in the document]
Comment (Oats87) [reply pkg/provisioningv2/rke2/planner/planner.go:188]: I'm not so sure this behavior makes sense to me where we start manipulating different conditions based on other conditions -- this is confusing for both debug and development purposes IMO.

Were we doing this before?

[the remark this answers is not in the document]
Comment (thedadams) [reply pkg/provisioningv2/rke2/planner/planner.go:188]: Are you suggesting that we only modify the `Provisioned` condition and leave out the `Updated` condition altogether?

File: pkg/provisioningv2/rke2/planner/planner.go (hunk 7 above)
Comment (Oats87) [reply pkg/provisioningv2/rke2/planner/planner.go:278]: No, that makes sense, the change here makes sense. I've been spending too much time between posix vs. golang recently.

File: pkg/provisioningv2/rke2/planner/planner.go (hunk 8 above)
Comment (Oats87) [reply pkg/provisioningv2/rke2/planner/planner.go:566]: I would either prefer we use a const for the `tierName` or switch it back to where it was before

File: pkg/controllers/provisioningv2/rke2/machinedrain/machinedrain.go (hunk 10 above)
[the remark this answers is not in the document]
Comment (Oats87) [reply pkg/controllers/provisioningv2/rke2/machinedrain/machinedrain.go:56]: Makes sense

File: pkg/provisioningv2/rke2/planner/planner.go (hunk 8 above)
Comment (thedadams) [reply pkg/provisioningv2/rke2/planner/planner.go:566]: I will switch it back.

File: pkg/provisioningv2/rke2/planner/planner.go (hunk 9 above)
[the remark this answers is not in the document]
Comment (thedadams) [reply pkg/provisioningv2/rke2/planner/planner.go]: I added a commit to only use the `Provisioned` condition. Let me know what you think.

**Review by jakefhyde — DISMISSED** [review]

File: pkg/provisioningv2/rke2/planner/drain.go (hunk 3 above)
Comment (thedadams) [reply pkg/provisioningv2/rke2/planner/drain.go]: Fixed

**Review by paynejacob — APPROVED** [review]

File: pkg/provisioningv2/rke2/planner/planner.go (hunk 7 above)
Comment (jiaqiluo) [reply pkg/provisioningv2/rke2/planner/planner.go:273]: Hi @thedadams , if a nil controlPlane is returned on line 281, will the defer function panic because it tries to access the namespace, name, and UID of the nil controlPlane?

**Review by jiaqiluo — CHANGES_REQUESTED** [review]

File: pkg/provisioningv2/rke2/planner/planner.go (hunk 7 above)
Comment (thedadams) [reply pkg/provisioningv2/rke2/planner/planner.go:273]: No, that is why I passed in the things we need from the control plane as arguments. By passing them as arguments to the deferred function, they are frozen in time.

When we were not passing them as arguments, then what you are saying is possible: line 281 returns a nil control plane, then the deferred function tries to use the control plane and panics.

Comment (jiaqiluo) [reply pkg/provisioningv2/rke2/planner/planner.go:273]: Got it!
Thanks for the explanation.

**Comment by thedadams** [comment]
I had to force push to resolve conflicts.

File: pkg/controllers/provisioningv2/rke2/machinedrain/machinedrain.go (hunk 4 above)
Comment (Oats87) [reply pkg/controllers/provisioningv2/rke2/machinedrain/machinedrain.go:247]: Sorry if I was unclear, this is actually not exactly what I meant. 

In this specific controller, we are looking for and manipulate a couple of annotations, i.e. `rke2.DrainDoneAnnotation`, `rke2.PreDrainAnnotation`, `rke2.PostDrainAnnotation`, `rke2.DrainErrorAnnotation`, `rke2.UncordonAnnotation`, etc. 

What I worry about is that this controller is taking a specific version of the secret, it is then processing the "input" annotations i.e. `rke2.DrainAnnotation` and then setting a bunch of other annotations based on that input. 

The issue with the `retry` here is that, let's say we have a situation where the `rke2.DrainAnnotation` is set, then immediately updated, the "input" secret is no longer the same as what we are currently processing and the output i.e. result of the event is going to have whatever specific annotations we're trying to set on the secret. Because the secret will have been updated while the secret is being processed through this controller, we will get a conflict and will be unable to set the annotation, but will continuously retry to set that annotation reflecting the "old" condition even though that has been updated at this point.

What I am thinking is before allowing the retry to continue, we should validate that our input, i.e. `rke2.DrainAnnotation`, `hook.Annotaiton`, etc. are all what we expect them to be every time we retrieve the secret from the client before setting our "result" annotations. This is to help prevent unnecessary thrashing of the controller, and keeps us closer to the conventional model of "re-enqueue if conflict"

**Review by Oats87 — COMMENTED** [review]
Other than the drain annotation set functionality, this all looks good to me.

**Review by paynejacob — APPROVED** [review]

**Review by jakefhyde — APPROVED** [review]

**Review by Oats87 — APPROVED** [review]

**Review by jiaqiluo — APPROVED** [review]
LGTM 💯
