### PR TITLE
Fix #50499 prevent index out of range panic when `after` is empty

### LINKED ISSUE #50499: [BUG] OCI repo causes Rancher 2.11.2 to crash
**Rancher Server Setup**
- Rancher version: 2.11.2
- Installation option (Docker install/Helm Chart): helm chart on k3s
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):

**Describe the bug**
Rancher deployment is stuck in CrashLoopBackoff after upgrade from 2.11.1 to 2.11.2

This is the log from the rancher pod:
```
panic: runtime error: index out of range [0] with length 0 [recovered]
        panic: runtime error: index out of range [0] with length 0

goroutine 2988 [running]:
k8s.io/apimachinery/pkg/util/runtime.handleCrash({0xb4a6ec8, 0x10de3e20}, {0x9e164e0, 0xc00bd23ae8}, {0x10de3e20, 0x0, 0x10000c01a8c5a00?})
        /root/.cache/go/modcache/k8s.io/apimachinery@v0.32.2/pkg/util/runtime/runtime.go:89 +0xe7
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc01a8c5a00?})
        /root/.cache/go/modcache/k8s.io/apimachinery@v0.32.2/pkg/util/runtime/runtime.go:59 +0x105
panic({0x9e164e0?, 0xc00bd23ae8?})
        /usr/lib64/go/1.24/src/runtime/panic.go:792 +0x132
github.com/rancher/rancher/pkg/catalogv2/oci.GenerateIndex.func2({0xc032459b08?, 0x7eb63e0?, 0xc0199c3ae8?})
        /app/pkg/catalogv2/oci/oci.go:180 +0x886
oras.land/oras-go/v2/registry/remote.(*Registry).repositories(0xc004ea9800, {0xb4a7148?, 0xc01f7d5830?}, {0x0, 0x0}, 0xc00cf3d430, {0xc02c24ef90?, 0xc0047d4096?})
        /root/.cache/go/modcache/oras.land/oras-go/v2@v2.4.0/registry/remote/registry.go:176 +0x615
oras.land/oras-go/v2/registry/remote.(*Registry).Repositories(0xc004ea9800, {0xb4a6ec8?, 0x10de3e20?}, {0x0, 0x0}, 0xc00cf3d430)
        /root/.cache/go/modcache/oras.land/oras-go/v2@v2.4.0/registry/remote/registry.go:134 +0x171
github.com/rancher/rancher/pkg/catalogv2/oci.GenerateIndex(_, {_, _}, _, {{0xc0047d4090, 0x2b}, 0x0, {0x0, 0x0}, {0x0, ...}, ...}, ...)
        /app/pkg/catalogv2/oci/oci.go:268 +0x6ca
github.com/rancher/rancher/pkg/controllers/dashboard/helm.(*OCIRepohandler).onClusterRepoChange(0xc0175caf80, {0xa3dd5c0?, 0xc016073b01?}, 0xc01c0e3b88)
        /app/pkg/controllers/dashboard/helm/repo_oci.go:161 +0xc68
github.com/rancher/wrangler/v3/pkg/generic.(*Controller[...].func1({0xb43d230?, 0xc01c0e3b88?})
        /root/.cache/go/modcache/github.com/rancher/wrangler/v3@v3.2.1/pkg/generic/controller.go:169 +0x44
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xa3dd5c0?, {0xc003a817d0?, 0xa5e7b4c?}, {0xb43d230?, 0xc01c0e3b88?})
        /root/.cache/go/modcache/github.com/rancher/lasso@v0.2.2/pkg/controller/sharedcontroller.go:29 +0x32
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc0019b2b40, {0xc003a817d0, 0x7}, {0xb43d230, 0xc004e04008})
        /root/.cache/go/modcache/github.com/rancher/lasso@v0.2.2/pkg/controller/sharedhandler.go:75 +0x203
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc00179ec60, {0xc003a817d0, 0x7})
        /root/.cache/go/modcache/github.com/rancher/lasso@v0.2.2/pkg/controller/controller.go:236 +0x12e
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc00179ec60, {0x7fb2b40, 0xc01a8c5a00})
        /root/.cache/go/modcache/github.com/rancher/lasso@v0.2.2/pkg/controller/controller.go:217 +0xd6
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc00179ec60)
        /root/.cache/go/modcache/github.com/rancher/lasso@v0.2.2/pkg/controller/controller.go:194 +0x3d
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
        /root/.cache/go/modcache/github.com/rancher/lasso@v0.2.2/pkg/controller/controller.go:183
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc001780808?)
        /root/.cache/go/modcache/k8s.io/apimachinery@v0.32.2/pkg/util/wait/backoff.go:226 +0x33
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0016680f0, {0xb41dce0, 0xc0029730e0}, 0x1, 0xc0000c6770)
        /root/.cache/go/modcache/k8s.io/apimachinery@v0.32.2/pkg/util/wait/backoff.go:227 +0xaf
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0016680f0, 0x3b9aca00, 0x0, 0x1, 0xc0000c6770)
        /root/.cache/go/modcache/k8s.io/apimachinery@v0.32.2/pkg/util/wait/backoff.go:204 +0x7f
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /root/.cache/go/modcache/k8s.io/apimachinery@v0.32.2/pkg/util/wait/backoff.go:161
created by github.com/rancher/lasso/pkg/controller.(*controller).run in goroutine 2428
        /root/.cache/go/modcache/github.com/rancher/lasso@v0.2.2/pkg/controller/controller.go:151 +0x354
```

I have an OCI repository added so I tried removing it, and then it starts successfully. Here's the OCI repo in question:

```
$ kubectl get clusterrepos forgejo -o json
{
    "apiVersion": "catalog.cattle.io/v1",
    "kind": "ClusterRepo",
    "metadata": {
        "creationTimestamp": "2025-05-30T16:00:40Z",
        "generation": 1,
        "name": "forgejo",
        "resourceVersion": "407824034",
        "uid": "ca7f3a2e-94c8-41aa-8166-d38b8006ab9c"
    },
    "spec": {
        "insecurePlainHttp": false,
        "url": "oci://code.forgejo.org/forgejo-helm/forgejo"
    },
    "status": {
        "conditions": [
            {
                "lastUpdateTime": "2025-05-30T16:00:40Z",
                "status": "True",
                "type": "FollowerDownloaded"
            }
        ],
        "observedGeneration": 0
    }
}
```

I think the offending change is this: https://github.com/rancher/rancher/commit/d73986762c9b4eab340277fdbccc8e5718734730

It checks ```after[0]``` without checking if that's valid. I can't really parse what the code is supposed to achieve so I'm not able to suggest a fix.

**To Reproduce**
Add OCI repo above to Rancher 2.11.2

**Result**
Crashes.

**Expected Result**
Not crashing.

### PR DESCRIPTION
**Pull request by l4zy0n3**
## Issue: 

[50499](https://github.com/rancher/rancher/issues/50499)

## Problem

Rancher pods go into a CrashLoopBackoff when an OCI repo after an upgrade from 2.11.1 to 2.11.2

```log
panic: runtime error: index out of range [0] with length 0 [recovered]                                                           panic: runtime error: index out of range [0] with length 0                                                                                                                                
```

## Solution

after[0] needs to evaluated only after we check that it is not empty and it is safe to do so, as suggested in the original issue [50499](https://github.com/rancher/rancher/issues/50499)
 
### Manual Testing

K3S version: 1.30.13-k3s1

1. Installed Rancher
2. Created an OCI repo with (oci://code.forgejo.org/forgejo-helm/forgejo)
3. Created an OCI repo using zot and added to Repositories
4. Kept under observation for a couple of hours
5. No crashes observed

### Automated Testing

* Test types added/modified:
    * Unit

Summary: _TODO_

### Regressions Considerations

_TODO_

Existing / newly added automated tests that provide evidence there are no regressions:
* _TODO_

### CODE REVIEW

**Comment by diogoasouza** [comment]
~~Shouldn't the target branch be release/v2.11?~~

**Review by rohitsakala — CHANGES_REQUESTED** [review]
Can a test be added so that such issues can be identified before itself.

**Review by diogoasouza — DISMISSED** [review]

**Comment by l4zy0n3** [comment]
Verified that the added test makes the code panic on the original version
 ```go
 if after, found := strings.CutPrefix(repository, ociClient.repository); found && (ociClient.repository == "" || after[0] == '/') {
```

File: pkg/catalogv2/oci/oci_test.go [hunk 1]
```diff
@@ -244,3 +246,57 @@ func TestGenerateIndex(t *testing.T) {
 		})
 	}
 }
+
+func TestGenerateIndexExactAndSubMatch(t *testing.T) {
```
Comment (diogoasouza) [inline pkg/catalogv2/oci/oci_test.go:250]: This is missing the case where `ociClient.repository == ""` e.i. where the user only provides the registry

**Review by diogoasouza — APPROVED** [review]

**Review by rohitsakala — APPROVED** [review]
Good work @l4zy0n3 . Thank you.
