### PR TITLE
[v2.9] fix: update 'promoted' ClusterRole when removing all permissions from RoleTemplate

### LINKED ISSUE #43292: [BUG] removing permission from role template doesn't propagate to 'promoted' clusterRole in downstream cluster
**Rancher Server Setup**
- Rancher version: 2.7.5

**Issue description:**
If you have a custom RoleTemplate which is being used in a downstream cluster, and you edit that RoleTemplate to remove a permission, it is not propagated to the role <roleName>-promoted in the downstream cluster.

**Business impact:**
RBAC is incorrect and has to be edited manually so users don't see objects they aren't supposed to

**Repro steps:**
kubectl apply attached roletemplate to the Rancher cluster
create a new standard user in Rancher and give them access to the Default Project with the custom role imported from step one
the user logs in and can explore the downstream cluster and go to More Resources > Rancher > Mgmt Clusters
now edit the RoleTemplate and remove the get / clusters / management.cattle.io permission
this should have removed the ability for the user to see step #3 but it didn't
an admin will have to go to explore the downstream cluster > More Resources > RBAC > ClusterRoles and find the <roleName>-promoted object and edit it to also remove the get / clusters / management.cattle.io permission
now the user can't see step #3

**Workaround:**
 step #6 above

**Actual behavior:**
Removed role permission does not propagate to downstream cluster

**Expected behavior:**
Removed role permission should propagate to downstream cluster

SURE-6805

### PR DESCRIPTION
**Pull request by enrichman**
Fix #43292 

## Issue: 
 - https://github.com/rancher/rancher/issues/43292
 
## Problem

This PR fixes the missing update of the `-promoted` ClusterRole when removing all the permissions.
The issue was due to a check of the length of the `newVerbs`. When `0` the update was skipped.
 
## Solution

To fix the issue I moved the check internally, removing the matching rules when no verbs are specified.

The small refactor of the func was made to have a more linear and clear flow, with some early returns/checks.
Added also some unit tests.

One note: in the previous implementation this was the check:

```go
if role, err := m.crLister.Get("", roleName); err == nil && role != nil {
	// update ClusterRole
}
// else create new ClusterRole
```

that means if an error occured (not only a "not found" error) then an update will be performed. I kept this behaviour for compatibility (other tests were failing) but I don't think it's actually needed.

```go
role, err := m.crLister.Get("", roleName)
// we try to create the role if not found, or if we get an error (for backward compatibility)
if apierrors.IsNotFound(err) || err != nil {
	// create
}
// else update
```
 
## Testing

Repro steps in the original issue are valid.

### Automated Testing

* Test types added/modified:
    * Unit

### CODE REVIEW

**Comment by bigkevmcd** [comment]
When reconciling things like this, I find that the `k8s.io/apimachinery/pkg/util/sets` package is really useful.

To figure out adds/removals is "easy" with the use of a sets.Set:

```go
package main

import (
    "fmt"

    "k8s.io/apimachinery/pkg/util/sets"
)

// Outputs:
// existing = [a b c d e]
// desired = [d e f]
// toBeDeleted = [c a b]
// toBeCreated = [f]
// toBeCheckedForUpdates = [d e]

func main() {
    existing := sets.New("a", "b", "c", "d", "e")
    desired := sets.New("d", "e", "f")

    fmt.Printf("existing = %v\n", existing.UnsortedList())
    fmt.Printf("desired = %v\n", desired.UnsortedList())

    toBeDeleted := existing.Difference(desired)
    fmt.Printf("toBeDeleted = %v\n", toBeDeleted.UnsortedList())

    toBeCreated := desired.Difference(existing)
    fmt.Printf("toBeCreated = %v\n", toBeCreated.UnsortedList())

    toBeCheckedForUpdates := desired.Intersection(existing)
    fmt.Printf("toBeCheckedForUpdates = %v\n", toBeCheckedForUpdates.UnsortedList())
}
```

The `map[string]struct{}` is the same as the underlying implementation in that package, but it provides a more human readable API?

File: pkg/controllers/managementuser/rbac/prtb_handler.go [hunk 1]
```diff
@@ -280,63 +280,105 @@ func (m *manager) checkForGlobalResourceRules(role *v3.RoleTemplate, resource st
...
+func (m *manager) reconcileRoleForProjectAccessToGlobalResource(resource string, roleName string, newVerbs map[string]struct{}, baseRule rbacv1.PolicyRule) (string, error) {
+	if roleName == "" {
+		return "", errors.New("cannot reconcile Role: missing roleName")
+	}
+	roleName = roleName + "-promoted"
+
+	role, err := m.crLister.Get("", roleName)
+
+	// we try to create the role if not found, or if we get an error (for backward compatibility)
+	if apierrors.IsNotFound(err) || err != nil {
```
Comment (raulcabello) [inline pkg/controllers/managementuser/rbac/prtb_handler.go:294]: if the err is not nil and different than not found I think we should return it. Imagine there is a temporary problem getting the role, but the role is there. This code would try to create a new role.

**Comment by enrichman** [comment]
@bigkevmcd nice, yes! Now it's much more readable. 
Also the comparison methods and the `List` are very convenient.

Done with eb0bce9

File: pkg/controllers/managementuser/rbac/prtb_handler_test.go [hunk 2]
```diff
@@ -186,3 +192,273 @@ func Test_manager_checkForGlobalResourceRules(t *testing.T) {
...
+					}, nil
+				},
+			},
+			clusterRolesMock: &typesrbacv1fakes.ClusterRoleInterfaceMock{
+				CreateFunc: func(in1 *v1.ClusterRole) (*v1.ClusterRole, error) {
+					assert.Fail(t, "unexpected call to ClusterRole Create")
+					return in1, nil
+				},
+				UpdateFunc: func(in1 *v1.ClusterRole) (*v1.ClusterRole, error) {
+					assert.Equal(t, &rbacv1.ClusterRole{
```
Comment (raulcabello) [inline pkg/controllers/managementuser/rbac/prtb_handler_test.go:357]: we don't check if this method is called, and maybe we could even check how many times was called? (just if it makes senses e.g it's called more than once). 
If update is never called this test would pass and this assert would never be verified.

File: pkg/controllers/managementuser/rbac/prtb_handler.go (hunk 1 above)
Comment (enrichman) [reply pkg/controllers/managementuser/rbac/prtb_handler.go:294]: This is very right, and it's what I did in the first implementation. But some old tests in a different part were failing, so I kept the old behaviour.
It's in the description of the PR and in the comment above.

Maybe some old folks could confirm if we can change this (@pmatseykanets?)

File: pkg/controllers/managementuser/rbac/prtb_handler_test.go (hunk 2 above)
Comment (enrichman) [reply pkg/controllers/managementuser/rbac/prtb_handler_test.go:357]: That's true. There are some `XXXCalls` methods in these mocks. I can probably add some more checks about this, and dropping the `assert.Fail` when we don't want the method being called.
I think that could be dropped anyway (test will panic if called)

File: pkg/controllers/managementuser/rbac/prtb_handler_test.go [hunk 3]
```diff
@@ -186,3 +192,273 @@ func Test_manager_checkForGlobalResourceRules(t *testing.T) {
...
+				},
+				UpdateFunc: func(in1 *v1.ClusterRole) (*v1.ClusterRole, error) {
+					assert.Fail(t, "unexpected call to ClusterRole Update")
+					return in1, nil
+				},
+			},
+			want: "",
+		},
+		{
+			name: "create a the role if get fails",
```
Comment (bigkevmcd) [inline pkg/controllers/managementuser/rbac/prtb_handler_test.go:404]:
```suggestion
			name: "create the role if get fails",
```
As above, I think the generic failure and "not found" should be separated https://pkg.go.dev/k8s.io/apimachinery/pkg/api/errors#NewNotFound might help :-)

File: pkg/controllers/managementuser/rbac/prtb_handler_test.go [hunk 4]
```diff
@@ -186,3 +192,273 @@ func Test_manager_checkForGlobalResourceRules(t *testing.T) {
...
+								Verbs:         []string{"create"},
+							},
+						},
+					}, in1)
+					return in1, nil
+				},
+			},
+			want: "myrole-promoted",
+		},
+		{
```
Comment (bigkevmcd) [inline pkg/controllers/managementuser/rbac/prtb_handler_test.go:375]: I'd like to see a test with multiple groups with different API Groups to ensure that this works.

File: pkg/controllers/managementuser/rbac/prtb_handler.go [hunk 5]
```diff
@@ -264,79 +264,109 @@ func (m *manager) checkForGlobalResourceRules(role *v3.RoleTemplate, resource st
...
+func (m *manager) reconcileRoleForProjectAccessToGlobalResource(resource string, roleName string, newVerbs sets.Set[string], baseRule rbacv1.PolicyRule) (string, error) {
+	if roleName == "" {
+		return "", errors.New("cannot reconcile Role: missing roleName")
+	}
+	roleName = roleName + "-promoted"
+
+	role, err := m.crLister.Get("", roleName)
+
+	// we try to create the role if not found, or if we get an error (for backward compatibility)
+	if apierrors.IsNotFound(err) || err != nil {
```
[the remark this answers is not in the document]
Comment (enrichman) [reply pkg/controllers/managementuser/rbac/prtb_handler.go:294]: Linking this other comment: https://github.com/rancher/rancher/pull/44765#discussion_r1524616839

File: pkg/controllers/managementuser/rbac/prtb_handler.go [hunk 6]
```diff
@@ -264,79 +264,109 @@ func (m *manager) checkForGlobalResourceRules(role *v3.RoleTemplate, resource st
...
-					role.Rules[i] = buildRule(resource, newVerbs)
-					added = true
-				}
-			}
-			if !added {
-				role.Rules = append(role.Rules, buildRule(resource, newVerbs))
+		_, err := m.clusterRoles.Create(clusterRole)
+		if err != nil {
+			if !apierrors.IsAlreadyExists(err) {
+				return "", errors.Wrapf(err, "couldn't create role %v", roleName)
```
[the remark this answers is not in the document]
Comment (enrichman) [reply pkg/controllers/managementuser/rbac/prtb_handler.go:313]: Yes, but it makes sense to update it. I'll do.

[the remark this answers is not in the document]
Comment (enrichman) [reply pkg/controllers/managementuser/rbac/prtb_handler.go]: Yes, but it makes sense to update it when we can. Done with f60200d

File: pkg/controllers/managementuser/rbac/prtb_handler.go [hunk 7]
```diff
@@ -264,79 +264,109 @@ func (m *manager) checkForGlobalResourceRules(role *v3.RoleTemplate, resource st
...
+	role = role.DeepCopy()
+
+	added := false
+	for i, rule := range role.Rules {
+		if slice.ContainsString(rule.Resources, resource) {
+			role.Rules[i] = buildRule(resource, newVerbs, baseRule)
+			added = true
+		}
+	}
+	if !added {
```
[the remark this answers is not in the document]
Comment (enrichman) [reply pkg/controllers/managementuser/rbac/prtb_handler.go:351]: Added some more tests here 6903dc8

File: pkg/controllers/managementuser/rbac/prtb_handler.go [hunk 8]
```diff
@@ -264,79 +264,109 @@ func (m *manager) checkForGlobalResourceRules(role *v3.RoleTemplate, resource st
...
+		if slice.ContainsString(rule.Resources, resource) {
+			currentVerbs.Insert(rule.Verbs...)
+			currentResourceNames.Insert(rule.ResourceNames...)
+		}
 	}
 
+	desiredResourceNames := sets.New(baseRule.ResourceNames...)
+
+	// if the currentVerbs and the currentResourceNames matches the desired state we can return
+	if currentVerbs.Equal(newVerbs) && currentResourceNames.Equal(desiredResourceNames) {
```
[the remark this answers is not in the document]
Comment (enrichman) [reply pkg/controllers/managementuser/rbac/prtb_handler.go:336]: Added some more tests here 6903dc8

File: pkg/controllers/managementuser/rbac/prtb_handler.go [hunk 9]
```diff
@@ -264,79 +264,109 @@ func (m *manager) checkForGlobalResourceRules(role *v3.RoleTemplate, resource st
...
-				for _, v := range rule.ResourceNames {
-					currentResourceNames[v] = struct{}{}
-				}
-			}
+// reconcileRoleForProjectAccessToGlobalResource ensure the clusterRole used to grant access of global resources
+// to users/groups in projects has appropriate rules for the given resource and verbs.
+// It returns the created or updated ClusterRole name, or blank "" if none were created or updated.
+// The roleName is used to find and create/update the relevant '<roleName>-promoted' ClusterRole.
+func (m *manager) reconcileRoleForProjectAccessToGlobalResource(resource string, roleName string, newVerbs sets.Set[string], baseRule rbacv1.PolicyRule) (string, error) {
+	if roleName == "" {
```
[the remark this answers is not in the document]
Comment (enrichman) [reply pkg/controllers/managementuser/rbac/prtb_handler.go:287]: Added some more tests here 6903dc8

File: pkg/controllers/managementuser/rbac/prtb_handler_test.go (hunk 3 above)
Comment (enrichman) [reply pkg/controllers/managementuser/rbac/prtb_handler_test.go]: Fix 678f8a1

File: pkg/controllers/managementuser/rbac/prtb_handler_test.go [hunk 10]
```diff
@@ -186,3 +192,370 @@ func Test_manager_checkForGlobalResourceRules(t *testing.T) {
...
+			name: "reconciling non existing ClusterRole with no verbs is no-op",
+			args: args{
+				rtName:   "myrole",
+				newVerbs: sets.New[string](),
+			},
+			crListerMockGetErr: errNotFound,
+			want:               "",
+		},
+		{
+			name: "existing ClusteRole will not update if no need to reconcile",
```
Comment (andreas-kupries) [inline pkg/controllers/managementuser/rbac/prtb_handler_test.go:246]:
```suggestion
			name: "existing ClusterRole will not update if no need to reconcile",
```

File: pkg/controllers/managementuser/rbac/prtb_handler_test.go [hunk 11]
```diff
@@ -186,3 +192,370 @@ func Test_manager_checkForGlobalResourceRules(t *testing.T) {
...
+						ResourceNames: []string{"local"},
+						Resources:     []string{"myresource"},
+						Verbs:         []string{"list", "delete"},
+					},
+				},
+			},
+			want: "myrole-promoted",
+		},
+		{
+			name: "non existing ClusteRole will create a new promoted ClusterRole",
```
Comment (andreas-kupries) [inline pkg/controllers/managementuser/rbac/prtb_handler_test.go:272]:
```suggestion
			name: "non existing ClusterRole will create a new promoted ClusterRole",
```

File: pkg/controllers/managementuser/rbac/prtb_handler_test.go [hunk 12]
```diff
@@ -186,3 +192,370 @@ func Test_manager_checkForGlobalResourceRules(t *testing.T) {
...
+					APIGroups:     []string{"management.cattle.io"},
+					ResourceNames: []string{"local"},
+					Resources:     []string{"myresource"},
+					Verbs:         []string{"get", "list"},
+				}},
+			},
+			want: "myrole-promoted",
+		},
+		{
+			name: "existing ClusteRole will update it adding missing rules",
```
Comment (andreas-kupries) [inline pkg/controllers/managementuser/rbac/prtb_handler_test.go:297]:
```suggestion
			name: "existing ClusterRole will update it adding missing rules",
```

File: pkg/controllers/managementuser/rbac/prtb_handler_test.go [hunk 13]
```diff
@@ -186,3 +192,370 @@ func Test_manager_checkForGlobalResourceRules(t *testing.T) {
...
+						ResourceNames: []string{"local"},
+						Resources:     []string{"myresource"},
+						Verbs:         []string{"delete", "list"},
+					},
+				},
+			},
+			want: "myrole-promoted",
+		},
+		{
+			name: "existing ClusteRole will update it",
```
Comment (andreas-kupries) [inline pkg/controllers/managementuser/rbac/prtb_handler_test.go:342]:
```suggestion
			name: "existing ClusterRole will update it",
```

**Review by andreas-kupries — CHANGES_REQUESTED** [review]
Not firm in the logic, and the changes made to it.
Saw a few comment typos tough.

File: pkg/controllers/managementuser/rbac/prtb_handler.go (hunk 1 above)
Comment (crobby) [reply pkg/controllers/managementuser/rbac/prtb_handler.go:295]: I think it makes sense to return the error when the error is NOT "not found".  If that change winds-up requiring larger changes to the other tests, I suppose it could all be done in a separate PR to keep this one on target.

**Comment by enrichman** [comment]
Thanks @andreas-kupries, fixed typos (and failing test) with 639abc9 :)

**Review by andreas-kupries — DISMISSED** [review]

File: pkg/controllers/managementuser/rbac/reconcile_roletemplate_test.go [hunk 14]
```diff
@@ -198,58 +214,106 @@ func TestEnsureGlobalResourcesRolesForPRTB(t *testing.T) {
...
+						{
+							Verbs:     []string{"create"},
+							APIGroups: []string{""},
+							Resources: []string{"namespaces"},
+						},
+					},
+				},
+			},
+		},
+		// {
```
Comment (crobby) [inline pkg/controllers/managementuser/rbac/reconcile_roletemplate_test.go:245]: If this test is no longer needed, it should be removed before merging.

Comment (enrichman) [reply pkg/controllers/managementuser/rbac/reconcile_roletemplate_test.go]: Yes, removed thanks! I had a chat with @pmatseykanets and the test case was unclear, nor correct.
Having a look when it was added (4479597c19bb4f7a74c304aa621932d213a05532) it was already failing, commenting the last test. Also the case of a "get role" failing seems to be not possible to have.

File: pkg/controllers/managementuser/rbac/reconcile_roletemplate_test.go [hunk 15]
```diff
@@ -26,6 +36,7 @@ func TestEnsureGlobalResourcesRolesForPRTB(t *testing.T) {
 	testCases := []testCase{
 		{
 			description:   "global resource rule should grant namespace read",
+			manager:       defaultManager,
```
Comment (bigkevmcd) [inline pkg/controllers/managementuser/rbac/reconcile_roletemplate_test.go:39]: You could've assumed the `defaultManager` if it was `nil` ?

**Review by bigkevmcd — COMMENTED** [review]
I'd really like to see some of the test boilerplate simplified, but, that is my personal preference.

Otherwise, looks good to me.

File: pkg/controllers/managementuser/rbac/reconcile_roletemplate_test.go [hunk 16]
```diff
@@ -198,58 +214,78 @@ func TestEnsureGlobalResourcesRolesForPRTB(t *testing.T) {
 				},
 			},
 		},
+		{
+			projectName: "testproject",
+			description: "error return when RoleTemplate client returns error",
+			manager: setupManager(
+				map[string]*v3.RoleTemplate{"create-ns": createNSRoleTemplate},
+				make(map[string]*v1.ClusterRole),
```
[the remark this answers is not in the document]
Comment (enrichman) [reply pkg/controllers/managementuser/rbac/reconcile_roletemplate_test.go:222]: Yes, I thought about that (I love the optional func pattern) but I didn't want to change too many things. But if you agree also about this I think that it worth the effort. :+1:

**Comment by enrichman** [comment]
Thanks @bigkevmcd, yes, the testing part is a bit unclear. I think it deserves a refactor. :+1:

**Review by andreas-kupries — APPROVED** [review]
Scanned for typos, none seen. Ok.

**Review by raulcabello — APPROVED** [review]
lgtm

**Review by raulcabello — COMMENTED** [review]
lgtm
